# Generated by Django 3.2 on 2022-11-21 17:23

import admins_work.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admins_work.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extra_service',
            field=models.ManyToManyField(blank=True, null=True, to='admins_work.ExtraServices'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile',
            field=models.CharField(max_length=10, validators=[admins_work.models.valid_mobile]),
        ),
    ]
