# Generated by Django 3.2 on 2022-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_work', '0002_auto_20221121_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='CheckInTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckOutTime',
            field=models.DateField(),
        ),
    ]
