# Generated by Django 3.2 on 2022-11-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_work', '0003_auto_20221121_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='CheckInTime',
            new_name='CheckInDate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='CheckOutTime',
            new_name='CheckOutDate',
        ),
    ]
